# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:slug/
gems:                [jekyll-paginate]

# Setup
title:               Source Code Tales
tagline:             "Tamás Szelei's coding blog"
description:         "This is my programming-related blog; I post rarely, but I try and put lots of effort into my posts."
baseurl:             ''
paginate:            5
excerpt_separator:   "-----"

# About/contact
author:
  name:              Tamás Szelei
  url:               https://twitter.com/szeleitamas
  email:             szelei.t@gmail.com

# Custom vars
version:             2.0.0
domain:              "http://szelei.me"
disqusid:            szeleime
